fix(ci): better change detection for E2E (#3047)
Fixes an issue when PR status checks did not report the status.
This is a common case when changed files are not in the list and workflow didn't trigger.

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -7,17 +7,6 @@ on:
     branches:
       - main
       - v*
-    paths:
-      - go.mod
-      - go.sum
-      - "**.go"
-      - "!**_test.go" # exclude test files to ignore unit test changes
-      - "test/**" # include test files in e2e again
-      - "!**.md"
-      - "Dockerfile.release"
-      - ".github/workflows/e2e.yaml"
-      - "chart/**"
-      - "manifests/**"
   workflow_dispatch:
 
 concurrency:
@@ -32,9 +21,24 @@ env:
   VCLUSTER_NAMESPACE: vcluster
 
 jobs:
+  detect_changes:
+    uses: loft-sh/github-actions/.github/workflows/detect-changes.yaml@v1
+    with:
+      paths: |
+        - "go.mod"
+        - "go.sum"
+        - "**.go"
+        - "!**_test.go" # exclude test files to ignore unit test changes
+        - "test/**" # include test files in e2e again
+        - "!**.md"
+        - "Dockerfile.release"
+        - ".github/workflows/e2e.yaml"
+        - "chart/**"
+        - "manifests/**"
   build:
     runs-on: ubuntu-latest
-    if: github.repository_owner == 'loft-sh' # do not run on forks
+    if: github.repository_owner == 'loft-sh' && needs.detect_changes.outputs.has_changed == 'true'
+    needs: detect_changes
     steps:
       - name: Checkout repository
         uses: actions/checkout@v5
@@ -64,7 +68,7 @@ jobs:
           # Build cli
           TELEMETRY_PRIVATE_KEY="" goreleaser build --single-target --snapshot --id vcluster-cli --clean --output ./vcluster
           # Build tests for cache
-          go test -mod=vendor -test.v -c ./test/e2e
+          go test -mod=vendor -test.v -c ./test/e2e || { echo "go test build failed"; exit 1; }
 
       - name: Upload syncer image to artifact
         uses: actions/upload-artifact@v4
@@ -81,6 +85,8 @@ jobs:
           retention-days: 7
 
   get-testsuites-dir:
+    needs: detect_changes
+    if: needs.detect_changes.outputs.has_changed == 'true'
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
@@ -96,8 +102,10 @@ jobs:
 
   vcluster-install-delete:
     name: Install and delete virtual cluster
-    needs: build
-
+    needs:
+      - build
+      - detect_changes
+    if: needs.detect_changes.outputs.has_changed == 'true'
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
@@ -149,6 +157,8 @@ jobs:
           ./hack/vcluster-install-scripts/test-helm-install.sh
 
   download-latest-cli:
+    needs: detect_changes
+    if: needs.detect_changes.outputs.has_changed == 'true'
     name: Download the latest vCluster cli
     runs-on: ubuntu-latest
     steps:
@@ -167,6 +177,8 @@ jobs:
     needs:
       - build
       - download-latest-cli
+      - detect_changes
+    if: needs.detect_changes.outputs.has_changed == 'true'
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -193,8 +205,8 @@ jobs:
           set -x
           kubectl cluster-info
           kubectl get pods -n kube-system
-          echo "kubectl config current-context:" $(kubectl config current-context)
-          echo "KUBECONFIG env var:" ${KUBECONFIG}
+          echo "kubectl config current-context: $(kubectl config current-context)"
+          echo "KUBECONFIG env var: ${KUBECONFIG}"
 
       - name: Download vcluster cli
         uses: actions/download-artifact@v5
@@ -253,7 +265,8 @@ jobs:
     needs:
       - build
       - get-testsuites-dir
-
+      - detect_changes
+    if: needs.detect_changes.outputs.has_changed == 'true'
     runs-on: ubuntu-latest
     permissions:
       id-token: write   # needed for OIDC → AWS
@@ -302,8 +315,8 @@ jobs:
           set -x
           kubectl cluster-info
           kubectl get pods -n kube-system
-          echo "kubectl config current-context:" $(kubectl config current-context)
-          echo "KUBECONFIG env var:" ${KUBECONFIG}
+          echo "kubectl config current-context: $(kubectl config current-context)"
+          echo "KUBECONFIG env var: ${KUBECONFIG}"
 
       - name: Download vcluster cli
         uses: actions/download-artifact@v5
@@ -321,41 +334,41 @@ jobs:
           set -x
 
           extraArgs=()
-          if [ ${{ matrix.test-suite-path }} == "./test/e2e_metrics_proxy" ]; then
+          if [ "${{ matrix.test-suite-path }}" = "./test/e2e_metrics_proxy" ]; then
             helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
-            helm upgrade --install metrics-server metrics-server/metrics-server --set args={--kubelet-insecure-tls} --set containerPort=4443 -n kube-system
+            helm upgrade --install metrics-server metrics-server/metrics-server --set "args={--kubelet-insecure-tls}" --set containerPort=4443 -n kube-system
           fi
 
-          if [ ${{ matrix.ha }} == "true" ]; then
+          if [ "${{ matrix.ha }}" = "true" ]; then
             haValues="-f ./test/values_ha.yaml"
           fi
 
-          if [ ${{ matrix.test-suite-path }} == "./test/e2e_target_namespace" ]; then
-            kubectl apply -f ${{ matrix.test-suite-path }}/role.yaml
+          if [ "${{ matrix.test-suite-path }}" = "./test/e2e_target_namespace" ]; then
+            kubectl apply -f "${{ matrix.test-suite-path }}/role.yaml"
           fi
 
-          if [ ${{ matrix.test-suite-path }} == "./test/e2e" ]; then
+          if [ "${{ matrix.test-suite-path }}" = "./test/e2e" ]; then
             kubectl create namespace from-host-sync-test
             kubectl create namespace from-host-sync-test-2
           fi
 
-          sed -i "s|REPLACE_REPOSITORY_NAME|${{ env.REPOSITORY_NAME }}|g" ${{ matrix.test-suite-path }}/../commonValues.yaml
-          sed -i "s|REPLACE_TAG_NAME|${{ env.TAG_NAME }}|g" ${{ matrix.test-suite-path }}/../commonValues.yaml
-          yq eval -i '.controlPlane.distro.${{ matrix.distribution }}.enabled = true'  ${{ matrix.test-suite-path }}/../commonValues.yaml
+          sed -i "s|REPLACE_REPOSITORY_NAME|${{ env.REPOSITORY_NAME }}|g" "${{ matrix.test-suite-path }}/../commonValues.yaml"
+          sed -i "s|REPLACE_TAG_NAME|${{ env.TAG_NAME }}|g" "${{ matrix.test-suite-path }}/../commonValues.yaml"
+          yq eval -i ".controlPlane.distro.${{ matrix.distribution }}.enabled = true" "${{ matrix.test-suite-path }}/../commonValues.yaml"
 
           docker load --input vcluster_syncer
           kind load image-archive vcluster_syncer
 
           chmod +x vcluster && sudo mv vcluster /usr/bin
 
-          vcluster create ${{ env.VCLUSTER_SUFFIX }} -n ${{ env.VCLUSTER_NAMESPACE }} \
+          vcluster create "${{ env.VCLUSTER_SUFFIX }}" -n "${{ env.VCLUSTER_NAMESPACE }}" \
           --create-namespace \
           --debug \
           --connect=false \
           --local-chart-dir ./chart \
           -f ./test/commonValues.yaml \
-          $haValues \
-          -f ${{ matrix.test-suite-path }}/values.yaml \
+          ${haValues:+$haValues} \
+          -f "${{ matrix.test-suite-path }}/values.yaml" \
           "${extraArgs[@]}"
         continue-on-error: true
 
